### ISSUE TITLE
"Add to home screen" has a problem with cookies

### ISSUE THREAD

**Issue by emdjensen** [nathandentzau/realtime-mbta-tracker#1]
When opening the app (after adding to home screen on iOS), after you click any of the lines, the app opens in the web browser to present the beta splash screen.  At this point, you have to "delete" the app shortcut from your home screen and add it again from Safari.  Also, even after completing the above steps, when you select "dashboard" from the slide-out menu, it opens the web browser.

**Comment by nathandentzau** [comment]
Fixed in the latest commit.
